# Generated by Django 3.1.2 on 2020-12-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20201201_1851'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialMedico',
            new_name='HistorialesMedico',
        ),
    ]
