# Generated by Django 3.1.2 on 2020-12-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0003_auto_20201201_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('detalle', models.CharField(max_length=64)),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=15, null=True)),
                ('lado', models.CharField(blank=True, max_length=15, null=True)),
                ('armazon', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('tipo_pago', models.CharField(max_length=64)),
                ('estado', models.CharField(max_length=64)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_paciente', to='turnos.pacientes')),
                ('producto', models.ManyToManyField(blank=True, related_name='pedidos_productos', to='ventas.Productos')),
            ],
        ),
    ]
