# Generated by Django 3.1.2 on 2020-12-02 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='vendedor',
            field=models.ForeignKey(default=1, limit_choices_to={'groups__name': 'Ventas'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_pedido', to='auth.user'),
            preserve_default=False,
        ),
    ]
