# Generated by Django 3.1.2 on 2020-12-01 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0002_medicos_turnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Medicos'}, on_delete=django.db.models.deletion.CASCADE, related_name='turno_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Medicos',
        ),
    ]
