# Generated by Django 3.1.2 on 2020-12-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20201201_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='asistencia',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
